name: Deploy database schema (production)

on:
  push:
    branches:
      - main
    paths:
      - "packages/database/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./packages/database

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Validate Prisma schema
        env:
          DATABASE_URL: "postgresql://postgres:test@localhost:5433/test_db"
          DIRECT_URL: "postgresql://postgres:test@localhost:5433/test_db"
        
        run: npx prisma validate

      - name: Test migrations on local database
        env:
          DATABASE_URL: "postgresql://postgres:test@localhost:5433/test_db"
          DIRECT_URL: "postgresql://postgres:test@localhost:5433/test_db"
        run: |
          # Test migrations on local database
          npx prisma migrate deploy
          # Verify the migration worked
          npx prisma migrate status
      
      - name: Check migration status
        env:
          DATABASE_URL: ${{ secrets.DATABASE_PRODUCTION_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_PRODUCTION_DIRECT_URL }}
        run: npx prisma migrate status

      - name: Deploy migrations to production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_PRODUCTION_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_PRODUCTION_DIRECT_URL }}
        run: npx prisma migrate deploy

      - name: Verify migration success
        env:
          DATABASE_URL: ${{ secrets.DATABASE_PRODUCTION_URL }}
          DIRECT_URL: ${{ secrets.DATABASE_PRODUCTION_DIRECT_URL }}
        run: |
          npx prisma migrate status
          npx prisma db execute --stdin <<< "SELECT current_database(), current_user, version();" --schema=./prisma/schema.prisma
          npx prisma db execute --stdin <<< "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';" --schema=./prisma/schema.prisma
        